<?php

use Illuminate\Support\Facades\Route;
use App\Http\Middleware\SystemAuth;
use App\Http\Middleware\CheckSystemAuth;
use App\Http\Middleware\AdminAuth;
use App\Http\Middleware\LoginAuth;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\BlogController;
use App\Http\Controllers\Admin\SetupController;
use App\Http\Controllers\Admin\CompanyController;
use App\Http\Controllers\Admin\BackgroundController;
use App\Http\Controllers\Client\ClientController;
use App\Http\Controllers\Client\NewsController;
use App\Http\Controllers\SystemController;
use App\Http\Controllers\Admin\ContactController;

Route::group(['middleware' => [SystemAuth::class]], function () {
    Route::group(['middleware' => [AdminAuth::class]], function () {
        Route::get('/admin', [DashboardController::class, 'index'])->name('admin');
        Route::get('/admin/logout', [AdminController::class, 'logout'])->name('logout');
        Route::get('/news', [BlogController::class, 'index'])->name('list_news');
        Route::get('/news/add-blog', [BlogController::class, 'add'])->name('add_news');
        Route::post('/news/save-blog', [BlogController::class, 'save'])->name('save_news');
        Route::post('/news/delete-blog', [BlogController::class, 'delete'])->name('delete_news');
        Route::get('/news/edit-blog/{id}', [BlogController::class, 'edit'])->name('edit_news');
        Route::get('/about_us', [BlogController::class, 'index'])->name('list_about_us');
        Route::get('/about_us/add-about-us', [BlogController::class, 'add'])->name('add_about_us');
        Route::post('/about_us/save-about-us', [BlogController::class, 'save'])->name('save_about_us');
        Route::post('/about_us/delete-about-us', [BlogController::class, 'delete'])->name('delete_about_us');
        Route::get('/about_us/edit-about-us/{id}', [BlogController::class, 'edit'])->name('edit_about_us');
        Route::get('/service', [BlogController::class, 'index'])->name('list_service');
        Route::get('/service/add-service', [BlogController::class, 'add'])->name('add_service');
        Route::post('/service/save-service', [BlogController::class, 'save'])->name('save_service');
        Route::post('/service/delete-service', [BlogController::class, 'delete'])->name('delete_service');
        Route::get('/service/edit-service/{id}', [BlogController::class, 'edit'])->name('edit_service');
        Route::get('/transport', [BlogController::class, 'index'])->name('list_transport');
        Route::get('/transport/add-transport', [BlogController::class, 'add'])->name('add_transport');
        Route::post('/transport/save-transport', [BlogController::class, 'save'])->name('save_transport');
        Route::post('/transport/delete-transport', [BlogController::class, 'delete'])->name('delete_transport');
        Route::get('/transport/edit-transport/{id}', [BlogController::class, 'edit'])->name('edit_transport');
        Route::get('/why_choose_us', [BlogController::class, 'index'])->name('list_why_choose_us');
        Route::get('/why_choose_us/add-why-choose-us', [BlogController::class, 'add'])->name('add_why_choose_us');
        Route::post('/why_choose_us/save-why-choose-us', [BlogController::class, 'save'])->name('save_why_choose_us');
        Route::post('/why_choose_us/delete-why-choose-us', [BlogController::class, 'delete'])->name('delete_why_choose_us');
        Route::get('/why_choose_us/edit-why-choose-us/{id}', [BlogController::class, 'edit'])->name('edit_why_choose_us');
        Route::get('/setup_column', [SetupController::class, 'index'])->name('setup_column');
        Route::post('/save_setup', [SetupController::class, 'save'])->name('save_setup');
        Route::get('/company', [CompanyController::class, 'index'])->name('company');
        Route::post('/save_company', [CompanyController::class, 'save'])->name('save_company');
        Route::get('/slider', [BlogController::class, 'index'])->name('list_slider');
        Route::get('/slider/add-slider', [BlogController::class, 'add'])->name('add_slider');
        Route::post('/slider/save-slider', [BlogController::class, 'save'])->name('save_slider');
        Route::post('/slider/delete-slider', [BlogController::class, 'delete'])->name('delete_slider');
        Route::get('/slider/edit-slider/{id}', [BlogController::class, 'edit'])->name('edit_slider');
        Route::get('/bg_about_us', [BackgroundController::class, 'index'])->name('bg_about_us');
        Route::post('/save_bg_about_us', [BackgroundController::class, 'save'])->name('save_bg_about_us');
        Route::get('/bg_why_choose_us', [BackgroundController::class, 'index'])->name('bg_why_choose_us');
        Route::post('/save_bg_why_choose_us', [BackgroundController::class, 'save'])->name('save_bg_why_choose_us');
        Route::get('/bg_contact', [BackgroundController::class, 'index'])->name('bg_contact');
        Route::post('/save_bg_contact', [BackgroundController::class, 'save'])->name('save_bg_contact');
        Route::get('/statistical', [BlogController::class, 'index'])->name('list_statistical');
        Route::get('/statistical/add-statistical', [BlogController::class, 'add'])->name('add_statistical');
        Route::post('/statistical/save-statistical', [BlogController::class, 'save'])->name('save_statistical');
        Route::post('/statistical/delete-statistical', [BlogController::class, 'delete'])->name('delete_statistical');
        Route::get('/statistical/edit-statistical/{id}', [BlogController::class, 'edit'])->name('edit_statistical');
        Route::get('/bg_statistical', [BackgroundController::class, 'index'])->name('bg_statistical');
        Route::post('/save_bg_statistical', [BackgroundController::class, 'save'])->name('save_bg_statistical');
        Route::get('/banner_news', [BackgroundController::class, 'index'])->name('banner_news');
        Route::post('/save_banner_news', [BackgroundController::class, 'save'])->name('save_banner_news');
        Route::get('/contact', [ContactController::class, 'index'])->name('list_contact');
        Route::get('/contact/view/{id}', [ContactController::class, 'view'])->name('view_contact');
    });
    Route::group(['middleware' => [LoginAuth::class]], function () {
        Route::get('/admin/login', function () {return view('admin.login');})->name('login');
        Route::post('/admin/login', [AdminController::class, 'login'])->name('login');
        //Route::get('/admin/signup', function () {return view('admin.signup');})->name('signup');
        //Route::post('/admin/signup', [AdminController::class, 'signup'])->name('signup');
    });
    Route::get('/', [ClientController::class, 'index'])->name('index');
    Route::post('/', [ClientController::class, 'contact'])->name('sendContact');
    Route::get('/tin-tuc', [NewsController::class, 'index'])->name('news');
    Route::get('/tin-tuc/{slug}', [NewsController::class, 'detail'])->name('news_detail');
});

Route::group(['middleware' => [CheckSystemAuth::class]], function () {
    Route::get('/system', [SystemController::class, 'index'])->name('system');
    Route::post('/system', [SystemController::class, 'save'])->name('save_system');
});